//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiForWorkPermitSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RequestProcess
    {
        public Nullable<long> EmployeeId { get; set; }
        public long RequestProcessSrNo { get; set; }
        public Nullable<long> VendorSrNo { get; set; }
        public Nullable<long> EmployeeDepartmentID { get; set; }
        public Nullable<System.DateTime> VisitStartTime { get; set; }
        public Nullable<System.DateTime> VisitEndTime { get; set; }
        public string VendorAccessories { get; set; }
        public Nullable<long> NoOfVendors { get; set; }
        public string VendorVisitResons { get; set; }
        public Nullable<System.DateTime> RequestProcessDate { get; set; }
        public string ActivityOwnerStatus { get; set; }
        public string AreaOwnerStatus { get; set; }
        public string SafetyStatus { get; set; }
        public string ContractorStatus { get; set; }
    
        public virtual tbl_DepartmentEmployeeRegistration tbl_DepartmentEmployeeRegistration { get; set; }
        public virtual tbl_VendorUserRegistration tbl_VendorUserRegistration { get; set; }
    }
}
