//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiForManageVisitors.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DesignationMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_DesignationMaster()
        {
            this.tbl_DepartmentEmployeeRegistration = new HashSet<tbl_DepartmentEmployeeRegistration>();
        }
    
        public long DesignationID { get; set; }
        public long DepartmentID { get; set; }
        public string DesignationName { get; set; }
        public Nullable<System.DateTime> DesignationCreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DepartmentEmployeeRegistration> tbl_DepartmentEmployeeRegistration { get; set; }
    }
}
