//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiForWorkPermitSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ContractorMaster
    {
        public long ContractorSrNo { get; set; }
        public string CompanyName { get; set; }
        public string ContractorName { get; set; }
        public string ContractorContactNo { get; set; }
        public Nullable<System.DateTime> ContractorCreateDate { get; set; }
    }
}
