//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiForManageVisitors.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VisitorUserRegistration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_VisitorUserRegistration()
        {
            this.tbl_RequestProcess = new HashSet<tbl_RequestProcess>();
        }
    
        public long VisitorSrNo { get; set; }
        public string VisitorUserID { get; set; }
        public string VisitorName { get; set; }
        public string VisitorAddress { get; set; }
        public string VisitorContactNo { get; set; }
        public string VisitorEmailID { get; set; }
        public string VisitorNatureOfWork { get; set; }
        public Nullable<long> VisitorContractorSrNo { get; set; }
        public string VisitorContractorCoNo { get; set; }
        public string VisitorPassword { get; set; }
        public Nullable<System.DateTime> VisitorRegistrationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RequestProcess> tbl_RequestProcess { get; set; }
    }
}
