//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiForManageVisitors.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DepartmentEmployeeRegistration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_DepartmentEmployeeRegistration()
        {
            this.tbl_RequestProcess = new HashSet<tbl_RequestProcess>();
        }
    
        public long EmployeeSrNo { get; set; }
        public string EmployeeTokenNo { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeAddress { get; set; }
        public string EmployeeContactNo { get; set; }
        public string EmployeeEmailID { get; set; }
        public Nullable<long> EmployeeDepartmentID { get; set; }
        public Nullable<long> EmployeeDesignationID { get; set; }
        public string EmployeePassword { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string DeviceTokenId { get; set; }
    
        public virtual tbl_DepartmentMaster tbl_DepartmentMaster { get; set; }
        public virtual tbl_DesignationMaster tbl_DesignationMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RequestProcess> tbl_RequestProcess { get; set; }
    }
}
