//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiForWorkPermitSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorkPermitSystemEntities : DbContext
    {
        public WorkPermitSystemEntities()
            : base("name=WorkPermitSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<tbl_ContractorMaster> tbl_ContractorMaster { get; set; }
        public virtual DbSet<tbl_DepartmentEmployeeRegistration> tbl_DepartmentEmployeeRegistration { get; set; }
        public virtual DbSet<tbl_DepartmentMaster> tbl_DepartmentMaster { get; set; }
        public virtual DbSet<tbl_DesignationMaster> tbl_DesignationMaster { get; set; }
        public virtual DbSet<tbl_RequestProcess> tbl_RequestProcess { get; set; }
        public virtual DbSet<tbl_VendorUserRegistration> tbl_VendorUserRegistration { get; set; }
    }
}
